# Generated by Django 5.2 on 2025-06-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0018_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extra_hour_charge_unlimited',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra hourly charge *after 12 hrs* for Unlimited KM plan', max_digits=6),
        ),
    ]
