# Generated by Django 5.2 on 2025-06-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0019_car_extra_hour_charge_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extra_km_per_hour_150km',
            field=models.PositiveIntegerField(default=0, help_text='Free km/hour after 12 hours for 150km plan'),
        ),
    ]
