# Generated by Django 5.2 on 2025-06-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0020_car_extra_km_per_hour_150km'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='kms_plan',
            field=models.CharField(default='150km', help_text='Chosen KM plan', max_length=20),
        ),
    ]
